/**
 * Sheliak Timewave (TW1) — verified reference data.
 *
 * Retrieval date: 2026-05-28.
 *
 * Sources (two independent primary artifacts; cross-check PASSED — the 384-number
 * Sheliak set is byte-for-byte identical across both):
 *   1. Peter Meyer's original DOS "Timewave Zero" program (2020 archive):
 *      https://archive.org/details/twz_20200405  (twz.zip)
 *        - TW_EN.C  : Peter Meyer's own wave-value source (rev. 1993-03-09)
 *        - DATA.TWZ : the build's active 384-number data set (== the Sheliak set)
 *   2. jasondrawdy/Omniwave (MIT) reimplementation bundling all four data sets:
 *      https://github.com/jasondrawdy/Omniwave
 *        - Omnigen/Resources/Data/DATA.TW1  : the Sheliak set (resource DATA2 ->
 *          WaveType.Sheliak in WaveGenerator.cs)
 *
 * Full algorithm + provenance + cross-check details:
 *   src/chart/references/sheliak-algorithm.md
 *
 * NOTE for Task 5: the data set has 384 entries (NOT 64). The wave function is the
 * self-similar sum from TW_EN.C with per-scale weight 64^i (NO "1/1.7^scale"
 * damping — that prototype factor is fabricated and must be discarded).
 */

/**
 * The 64 I Ching hexagrams in King Wen sequence, encoded as 6-bit integers with
 * bit 0 = bottom line, yang(solid) = 1, yin(broken) = 0. (Hexagram 1 = 63,
 * hexagram 2 = 0.) This is the conceptual seed; the running timewave consumes
 * DATA_SET_REFERENCE directly rather than recomputing from this.
 */
export const KING_WEN_REFERENCE: readonly number[] = [
  63, 0, 17, 34, 23, 58, 2, 16, 55, 59, 7, 56, 61, 47, 4, 8,
  25, 38, 3, 48, 41, 37, 32, 1, 57, 39, 33, 30, 18, 45, 28, 14,
  60, 15, 40, 5, 53, 43, 20, 10, 35, 49, 31, 62, 24, 6, 26, 22,
  29, 46, 9, 36, 52, 11, 13, 44, 54, 27, 50, 19, 51, 12, 21, 42,
];

/**
 * The Sheliak (TW1) number set — exactly 384 non-negative integers. This is the
 * input to the timewave fractal-sum function. Verified identical between the DOS
 * program's DATA.TWZ and Omniwave's DATA.TW1.
 */
export const DATA_SET_REFERENCE: readonly number[] = [
  0, 0, 0, 2, 7, 4, 3, 2, 6, 8, 13, 5, 26, 25, 24, 15,
  13, 16, 14, 19, 17, 24, 20, 25, 63, 60, 56, 55, 47, 53, 36, 38,
  39, 43, 39, 35, 22, 24, 22, 21, 29, 30, 27, 26, 26, 21, 23, 19,
  57, 62, 61, 55, 57, 57, 35, 50, 40, 29, 28, 26, 50, 51, 52, 61,
  60, 60, 42, 42, 43, 43, 42, 41, 45, 41, 46, 23, 35, 34, 21, 21,
  19, 51, 40, 49, 29, 29, 31, 40, 36, 33, 29, 26, 30, 16, 18, 14,
  66, 64, 64, 56, 53, 57, 49, 51, 47, 44, 46, 47, 56, 51, 53, 25,
  37, 30, 31, 28, 30, 36, 35, 22, 28, 32, 27, 32, 34, 35, 52, 49,
  48, 51, 51, 53, 40, 43, 42, 26, 30, 28, 55, 41, 53, 52, 51, 47,
  61, 64, 65, 39, 41, 41, 22, 21, 23, 43, 41, 38, 24, 22, 24, 14,
  17, 19, 52, 50, 47, 42, 40, 42, 26, 27, 27, 34, 38, 33, 44, 44,
  42, 41, 40, 37, 33, 31, 26, 44, 34, 38, 46, 44, 44, 36, 37, 34,
  36, 36, 36, 38, 43, 38, 27, 26, 30, 32, 37, 29, 50, 49, 48, 29,
  37, 36, 10, 19, 17, 24, 20, 25, 53, 52, 50, 53, 57, 55, 34, 44,
  45, 13, 9, 5, 34, 26, 32, 31, 41, 42, 31, 32, 30, 21, 19, 23,
  43, 36, 31, 47, 45, 43, 47, 62, 52, 41, 36, 38, 46, 47, 40, 43,
  42, 42, 36, 38, 43, 53, 52, 53, 47, 49, 48, 47, 41, 44, 15, 11,
  19, 51, 40, 49, 23, 23, 25, 34, 30, 27, 7, 4, 4, 32, 22, 32,
  68, 70, 66, 68, 79, 71, 43, 45, 41, 38, 40, 41, 24, 25, 23, 35,
  33, 38, 43, 50, 48, 18, 17, 26, 34, 38, 33, 38, 40, 41, 34, 31,
  30, 33, 33, 35, 28, 23, 22, 26, 30, 26, 75, 77, 71, 62, 63, 63,
  37, 40, 41, 49, 47, 51, 32, 37, 33, 49, 47, 44, 32, 38, 28, 38,
  39, 37, 22, 20, 17, 44, 50, 40, 32, 33, 33, 40, 44, 39, 32, 32,
  40, 39, 34, 41, 33, 33, 32, 32, 38, 36, 22, 20, 20, 12, 13, 10,
];

/**
 * Published spot-check pairs: t = days before the zero point, value = f(t).
 * Generated by compiling Peter Meyer's own TW_EN.C (portable multiply/divide
 * variant) against the verified Sheliak DATA.TWZ. A correct reimplementation of
 * the wave function must reproduce these (note f(24576) = 0.046875 = 3/64 and
 * f(262144) = f(4 * 64^3) = 0.9479166..., which are clean self-similarity anchors).
 */
export const REFERENCE_SAMPLES: ReadonlyArray<{ t: number; value: number }> = [
  { t: 1, value: 0.00000361601512 },
  { t: 2, value: 0.00000290643601 },
  { t: 7, value: 0.00001124540965 },
  { t: 67, value: 0.00016383330027 },
  { t: 365.25, value: 0.00094825029373 },
  { t: 2349, value: 0.00579667091370 },
  { t: 4096, value: 0.01481119791667 },
  { t: 24576, value: 0.04687500000000 },
  { t: 67449, value: 0.23081421852112 },
  { t: 262144, value: 0.94791666666667 },
  { t: 1000000, value: 6.78441111246745 },
  { t: 5125730, value: 18.76276688348679 },
];
